spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sgdrs
    username: postgres
    password: Cinza229702

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  jpa:
    hibernate:
      ddl-auto: validate
    show_sql: true
    properties:
      hibernate:
        format_sql: true

  server:
    error:
      include-message: always
    port: 8080

  logging:
    level:
      org:
        springframework:
          security: DEBUG
        hibernate:
          orm:
            jdbc:
              bind: trace

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    metrics:
      enabled: false
    health:
      show-components: always
      show-details: always